### ISSUE TITLE
Crash when setting google provider variables

### ISSUE THREAD

**Issue by pputman12** [akeyless-community/terraform-provider-akeyless#43]
I'm getting this error after adding changing a provider.tf to be set with variables.  I understand you can't set variables for the actual backend/state setting, but I should be able to set them in the akeyless and google providers.  Thanks

terraform {
  backend "gcs" {
    bucket = "akeyless-terraform-state-demo"
    prefix = "access-roles/okta/akeyless-admins"
  }

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 4.9.0"
    }
    akeyless = {
      source  = "akeyless-community/akeyless"
      version = "1.1.10"
    }
  }
}

provider "akeyless" {
  api_gateway_address = var.api_gateway_address
  api_key_login {
    access_id  = var.access_id
    access_key = var.access_key
  }
}

provider "google" {
  project = var.project
  region  = var.region
}

patrick@R90XQ0G937 akeyless-admins % terraform apply
module.access_role_okta.akeyless_role.access_role: Refreshing state... [id=okta/akeyless-admins]
╷
│ Error: Request cancelled
│ 
│   with module.access_role_okta.akeyless_role.access_role,
│   on .terraform/modules/access_role_okta/terraform/akeyless-modules/akeyless-access-role/main.tf line 2, in resource "akeyless_role" "access_role":
│    2: resource "akeyless_role" "access_role" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-akeyless_v1.1.10 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1055bf988]

goroutine 57 [running]:
github.com/akeylesslabs/terraform-provider-akeyless/akeyless.resourceRoleRead(0x14000392000, {0x105aa4fc0, 0x140003c0d70})
	github.com/akeylesslabs/terraform-provider-akeyless/akeyless/resource_role.go:217 +0x108
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x105782c7f?, {0x105bc4f58?, 0x14000047bc0?}, 0x24?, {0x105aa4fc0?, 0x140003c0d70?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:335 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140000fddc0, {0x105bc4f58, 0x14000047bc0}, 0x14000560ee0, {0x105aa4fc0, 0x140003c0d70})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x30c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400000d4e8, {0x105bc4f58, 0x14000047bc0}, 0x14000047c00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x380
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0x140004ce0e0, {0x105bc5000?, 0x14000828d20?}, 0x1400058ca20)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x240
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x105b3a4e0?, 0x140004ce0e0}, {0x105bc5000, 0x14000828d20}, 0x1400058c9c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000326a80, {0x105bc8da0, 0x1400027e000}, 0x1400082ac60, 0x140004cc690, 0x1063a0110, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0xadc
google.golang.org/grpc.(*Server).handleStream(0x14000326a80, {0x105bc8da0, 0x1400027e000}, 0x1400082ac60, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.37.0/server.go:878 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x290

Error: The terraform-provider-akeyless_v1.1.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tuvia-akeyless** [comment]
fixed in terraform  version  1.1.11
