### ISSUE TITLE
Provider Crash

### ISSUE THREAD

**Issue by pputman-clabs** [akeyless-community/terraform-provider-akeyless#46]
I was just configuring access roles and I crashed the provider.

Stack trace from the terraform-provider-akeyless_v1.1.11 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 44 [running]:
github.com/akeylesslabs/terraform-provider-akeyless/akeyless.deleteRoleAuthMethods({0x1053b4f90, 0x14000036078}, {0x14000098410?, 0x1400067e400?}, {0x140003e1cb0, 0x1, 0x1?}, {0x105294fc0?, 0x140003e0e30?})
	github.com/akeylesslabs/terraform-provider-akeyless/akeyless/resource_role.go:548 +0x324
github.com/akeylesslabs/terraform-provider-akeyless/akeyless.assocRoleAuthMethod({0x1053b4f90, 0x14000036078}, {0x1400060e040, 0x1a}, {0x140003e1cb0?, 0x3d?, 0x140008592c8?}, {0x140003e1cc0, 0x1, 0x1}, ...)
	github.com/akeylesslabs/terraform-provider-akeyless/akeyless/resource_role.go:521 +0x58
github.com/akeylesslabs/terraform-provider-akeyless/akeyless.resourceRoleUpdate.func1()
	github.com/akeylesslabs/terraform-provider-akeyless/akeyless/resource_role.go:267 +0x70
github.com/akeylesslabs/terraform-provider-akeyless/akeyless.resourceRoleUpdate(0x140008755a0?, {0x105294fc0, 0x140003e0e30})
	github.com/akeylesslabs/terraform-provider-akeyless/akeyless/resource_role.go:311 +0x59c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x10524a2c0?, {0x1053b4f58?, 0x140005c2200?}, 0x24?, {0x105294fc0?, 0x140003e0e30?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:352 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000fddc0, {0x1053b4f58, 0x140005c2200}, 0x140001c00e0, 0x140008755a0, {0x105294fc0, 0x140003e0e30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:464 +0x480
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000d4e8, {0x1053b4f58, 0x140005c2200}, 0x140006ac0f0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x868
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0x140005520c0, {0x1053b5000?, 0x140008341b0?}, 0x1400083e800?)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x64
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10532a4e0?, 0x140005520c0}, {0x1053b5000, 0x140008341b0}, 0x140003806c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000322a80, {0x1053b8da0, 0x1400027c000}, 0x1400083a000, 0x14000550690, 0x105b90140, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0xadc
google.golang.org/grpc.(*Server).handleStream(0x14000322a80, {0x1053b8da0, 0x1400027c000}, 0x1400083a000, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.37.0/server.go:878 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x290

Error: The terraform-provider-akeyless_v1.1.11 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tuvia-akeyless** [comment]
fixed in terraform provider version 1.1.12
