### ISSUE TITLE
Azure AD Provider client secret variable should be sensitive

### ISSUE THREAD

**Issue by nbaju1** [akeyless-community/terraform-provider-akeyless#52]
The variable` azure_client_secret ` on the `akeyless_producer_azure` resource should be declared as sensitive in the schema. Currently can't use a secret pipeline variable in AzDo to pass as input to this field (this works for the `access_key` variable on the provider resource).

**Comment by tuvia-akeyless** [comment]
resolved in terraform version 1.1.16
