### ISSUE TITLE
akeyless_auth_method_oauth2 resource does not support a jwks json input

### ISSUE THREAD

**Issue by ppejovic** [akeyless-community/terraform-provider-akeyless#62]
The `akeyless_auth_method_oauth2` resource currently only supports a jwks uri for the JWKS:

https://github.com/akeyless-community/terraform-provider-akeyless/blob/9afc7c0d390a40aa1dd88fd8ff2d7dfd9de56732/akeyless/resource_auth_method_oauth2.go#L52-L55

Due to our jwks endpoint being private, we have to configure the oauth2 method in the akeyless ui using the available JWKS JSON option. This is not supported in the resource, despite being available in the api (jwks-json-data and jwks-json-file params):

https://docs.akeyless.io/reference/createauthmethodoauth2

**Comment by renanaAkeyless** [comment]
added in version 1.2.2
